# Generated by Django 3.2.17 on 2023-02-13 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('content', models.TextField(blank=True)),
                ('profile_image', models.ImageField(default='../l8qeltsgnl3r9lyfrg5v', upload_to='images/')),
                ('balance', models.IntegerField(null=True)),
                ('gym_category', models.IntegerField(default=1)),
                ('tutorial_level', models.IntegerField(default=1)),
                ('trainer_type', models.TextField(default='Trainer')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
