# Generated by Django 3.2.17 on 2023-02-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='elite_level',
            field=models.IntegerField(default=1),
        ),
    ]
