# Generated by Django 3.2.17 on 2023-02-15 20:41

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('caught', models.DateTimeField(auto_now_add=True)),
                ('sprite_front', models.ImageField(upload_to='images/')),
                ('sprite_back', models.ImageField(upload_to='images/')),
                ('nickname', models.CharField(blank=True, max_length=25)),
                ('evolve_from', models.IntegerField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('pokedex_index', models.IntegerField()),
                ('moveset', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=4)),
                ('level', models.IntegerField()),
                ('stats', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=6)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pokedex_index'],
            },
        ),
    ]
